a = input('Digite algo: ')
print('O tipo primitivo disto é ', type(a))
print('Tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está com letras maiúsculas? ',a.isupper())
print('Está em minúsculo? ', a.islower())
